/**
 * Pre-loaded demo data for live presentation mode.
 * Complete 5-day Tokyo trip with realistic hotels, activities,
 * itinerary, weather, and budget breakdown.
 */

import type { PlanResponse, PlanRequest } from "@/types/api";
import type {
  TravelPlannerCore,
  HotelOption,
  Activity,
  OptimizedItinerary,
  DestinationAnalysis,
  WeatherForecast,
} from "@/types/core";

// ─── Request ──────────────────────────────────────────────────────
export const DEMO_REQUEST: PlanRequest = {
  destination: "Tokyo, Japan",
  start_date: "2026-04-01",
  end_date: "2026-04-06",
  budget: 5000,
  currency: "USD",
  group_size: 2,
  interests: "culture, gastronomy, temples, technology, photography",
};

// ─── Hotels ───────────────────────────────────────────────────────
const HOTELS: HotelOption[] = [
  {
    id: "hotel-park-hyatt",
    name: "Park Hyatt Tokyo",
    address: "3-7-1-2 Nishi-Shinjuku, Shinjuku-ku, Tokyo",
    coordinates: { lat: 35.6867, lng: 139.6917 },
    stars: 5,
    price_per_night: 420,
    currency: "USD",
    amenities: ["Spa", "Pool", "Gym", "Restaurant", "Bar", "Free WiFi", "Concierge"],
    reviews_score: 4.8,
    distance_to_center_km: 2.1,
    score: 95,
  },
  {
    id: "hotel-prince-gallery",
    name: "The Prince Gallery Tokyo Kioicho",
    address: "1-2 Kioicho, Chiyoda-ku, Tokyo",
    coordinates: { lat: 35.6832, lng: 139.7356 },
    stars: 5,
    price_per_night: 380,
    currency: "USD",
    amenities: ["Spa", "Gym", "Restaurant", "Bar", "Free WiFi", "Rooftop"],
    reviews_score: 4.7,
    distance_to_center_km: 0.8,
    score: 92,
  },
  {
    id: "hotel-gracery",
    name: "Hotel Gracery Shinjuku",
    address: "1-19-1 Kabukicho, Shinjuku-ku, Tokyo",
    coordinates: { lat: 35.6942, lng: 139.7013 },
    stars: 4,
    price_per_night: 180,
    currency: "USD",
    amenities: ["Restaurant", "Free WiFi", "Laundry", "A/C"],
    reviews_score: 4.4,
    distance_to_center_km: 1.5,
    score: 88,
  },
  {
    id: "hotel-granbell",
    name: "Shinjuku Granbell Hotel",
    address: "2-14-5 Kabukicho, Shinjuku-ku, Tokyo",
    coordinates: { lat: 35.6955, lng: 139.7035 },
    stars: 3,
    price_per_night: 120,
    currency: "USD",
    amenities: ["Free WiFi", "Restaurant", "A/C", "Laundry"],
    reviews_score: 4.2,
    distance_to_center_km: 1.6,
    score: 84,
  },
  {
    id: "hotel-mimaru",
    name: "MIMARU Tokyo Ueno",
    address: "5-20-5 Higashi-Ueno, Taito-ku, Tokyo",
    coordinates: { lat: 35.7128, lng: 139.7760 },
    stars: 3,
    price_per_night: 95,
    currency: "USD",
    amenities: ["Kitchen", "Free WiFi", "Laundry", "A/C"],
    reviews_score: 4.3,
    distance_to_center_km: 3.2,
    score: 81,
  },
];

// ─── Activities ───────────────────────────────────────────────────
const HOURS_ALL_DAY: Record<string, string> = {
  monday: "06:00-17:00",
  tuesday: "06:00-17:00",
  wednesday: "06:00-17:00",
  thursday: "06:00-17:00",
  friday: "06:00-17:00",
  saturday: "06:00-17:00",
  sunday: "06:00-17:00",
};

const ACTIVITIES: Activity[] = [
  // Day 1 — Asakusa / Ueno
  {
    id: "act-sensoji",
    name: "Senso-ji Temple",
    category: "temple",
    address: "2-3-1 Asakusa, Taito-ku, Tokyo",
    coordinates: { lat: 35.7148, lng: 139.7967 },
    duration_minutes: 90,
    price: 0,
    currency: "USD",
    opening_hours: HOURS_ALL_DAY,
    requires_booking: false,
    indoor: false,
    description: "Tokyo's oldest and most significant Buddhist temple, founded in 645 AD. The iconic Kaminarimon gate and Nakamise shopping street lead to the main hall.",
    score: 0.96,
  },
  {
    id: "act-nakamise",
    name: "Nakamise Shopping Street",
    category: "shopping",
    address: "1-36-3 Asakusa, Taito-ku, Tokyo",
    coordinates: { lat: 35.7126, lng: 139.7966 },
    duration_minutes: 60,
    price: 15,
    currency: "USD",
    opening_hours: { monday: "10:00-18:00", tuesday: "10:00-18:00", wednesday: "10:00-18:00", thursday: "10:00-18:00", friday: "10:00-18:00", saturday: "10:00-19:00", sunday: "10:00-19:00" },
    requires_booking: false,
    indoor: false,
    description: "One of Japan's oldest shopping streets with over 50 shops selling traditional snacks, souvenirs, and crafts along the path to Senso-ji Temple.",
    score: 0.85,
  },
  {
    id: "act-ueno-park",
    name: "Ueno Park",
    category: "park",
    address: "Uenokoen, Taito-ku, Tokyo",
    coordinates: { lat: 35.7146, lng: 139.7741 },
    duration_minutes: 120,
    price: 0,
    currency: "USD",
    opening_hours: HOURS_ALL_DAY,
    requires_booking: false,
    indoor: false,
    description: "Spacious public park famous for cherry blossoms in spring. Home to several museums, a zoo, and Shinobazu Pond. Over 1,000 cherry trees bloom in April.",
    score: 0.90,
  },
  // Day 2 — Shibuya / Harajuku
  {
    id: "act-meiji-shrine",
    name: "Meiji Shrine",
    category: "temple",
    address: "1-1 Yoyogikamizonocho, Shibuya-ku, Tokyo",
    coordinates: { lat: 35.6764, lng: 139.6993 },
    duration_minutes: 90,
    price: 0,
    currency: "USD",
    opening_hours: HOURS_ALL_DAY,
    requires_booking: false,
    indoor: false,
    description: "Shinto shrine dedicated to Emperor Meiji and Empress Shoken, set in a 170-acre forest with 120,000 trees donated from across Japan.",
    score: 0.94,
  },
  {
    id: "act-takeshita",
    name: "Takeshita Street",
    category: "shopping",
    address: "1-17 Jingumae, Shibuya-ku, Tokyo",
    coordinates: { lat: 35.6718, lng: 139.7026 },
    duration_minutes: 60,
    price: 20,
    currency: "USD",
    opening_hours: { monday: "10:00-20:00", tuesday: "10:00-20:00", wednesday: "10:00-20:00", thursday: "10:00-20:00", friday: "10:00-20:00", saturday: "10:00-21:00", sunday: "10:00-21:00" },
    requires_booking: false,
    indoor: false,
    description: "The epicenter of Japanese youth culture and fashion. Colorful shops, crepe stands, and kawaii culture at every turn.",
    score: 0.82,
  },
  {
    id: "act-shibuya-crossing",
    name: "Shibuya Crossing",
    category: "landmark",
    address: "2-2-1 Dogenzaka, Shibuya-ku, Tokyo",
    coordinates: { lat: 35.6595, lng: 139.7004 },
    duration_minutes: 30,
    price: 0,
    currency: "USD",
    opening_hours: HOURS_ALL_DAY,
    requires_booking: false,
    indoor: false,
    description: "The world's busiest pedestrian crossing. Up to 3,000 people cross at once during peak hours. Best viewed from Shibuya Sky or Starbucks above.",
    score: 0.88,
  },
  {
    id: "act-teamlab-borderless",
    name: "teamLab Borderless",
    category: "museum",
    address: "Azabudai Hills, Minato-ku, Tokyo",
    coordinates: { lat: 35.6590, lng: 139.7320 },
    duration_minutes: 120,
    price: 38,
    currency: "USD",
    opening_hours: { monday: "10:00-21:00", tuesday: "10:00-21:00", wednesday: "10:00-21:00", thursday: "10:00-21:00", friday: "10:00-21:00", saturday: "10:00-21:00", sunday: "10:00-21:00" },
    requires_booking: true,
    indoor: true,
    description: "Immersive digital art museum where artworks flow beyond boundaries. 50+ interactive installations that respond to your presence.",
    score: 0.93,
  },
  // Day 3 — Imperial Palace / Akihabara
  {
    id: "act-imperial-palace",
    name: "Imperial Palace East Gardens",
    category: "historic",
    address: "1-1 Chiyoda, Chiyoda-ku, Tokyo",
    coordinates: { lat: 35.6852, lng: 139.7528 },
    duration_minutes: 90,
    price: 0,
    currency: "USD",
    opening_hours: { monday: "Closed", tuesday: "09:00-16:30", wednesday: "09:00-16:30", thursday: "09:00-16:30", friday: "Closed", saturday: "09:00-16:30", sunday: "09:00-16:30" },
    requires_booking: false,
    indoor: false,
    description: "Former site of Edo Castle, now a public garden with moats, stone walls, and seasonal flowers. Free admission with beautiful views.",
    score: 0.87,
  },
  {
    id: "act-akihabara",
    name: "Akihabara Electric Town",
    category: "shopping",
    address: "Sotokanda, Chiyoda-ku, Tokyo",
    coordinates: { lat: 35.6984, lng: 139.7731 },
    duration_minutes: 120,
    price: 30,
    currency: "USD",
    opening_hours: { monday: "10:00-21:00", tuesday: "10:00-21:00", wednesday: "10:00-21:00", thursday: "10:00-21:00", friday: "10:00-21:00", saturday: "10:00-21:00", sunday: "10:00-21:00" },
    requires_booking: false,
    indoor: true,
    description: "Tokyo's electronics and anime mecca. Multi-story arcades, manga shops, maid cafes, and cutting-edge tech stores.",
    score: 0.86,
  },
  {
    id: "act-tokyo-anime",
    name: "Tokyo Anime Center",
    category: "entertainment",
    address: "UDX Building 4F, 4-14-1 Sotokanda, Chiyoda-ku",
    coordinates: { lat: 35.7001, lng: 139.7712 },
    duration_minutes: 60,
    price: 12,
    currency: "USD",
    opening_hours: { monday: "11:00-19:00", tuesday: "11:00-19:00", wednesday: "11:00-19:00", thursday: "11:00-19:00", friday: "11:00-19:00", saturday: "11:00-20:00", sunday: "11:00-20:00" },
    requires_booking: false,
    indoor: true,
    description: "Exhibition space showcasing the latest in Japanese animation with rotating exhibits, exclusive merchandise, and interactive displays.",
    score: 0.78,
  },
  // Day 4 — Tsukiji / Odaiba
  {
    id: "act-tsukiji",
    name: "Tsukiji Outer Market",
    category: "food",
    address: "4-16-2 Tsukiji, Chuo-ku, Tokyo",
    coordinates: { lat: 35.6654, lng: 139.7707 },
    duration_minutes: 120,
    price: 40,
    currency: "USD",
    opening_hours: { monday: "05:00-14:00", tuesday: "05:00-14:00", wednesday: "Closed", thursday: "05:00-14:00", friday: "05:00-14:00", saturday: "05:00-14:00", sunday: "05:00-14:00" },
    requires_booking: false,
    indoor: false,
    description: "Tokyo's premier food market with 400+ vendors. Fresh sushi, tamagoyaki, wagyu beef skewers, and Japanese street food at its finest.",
    score: 0.95,
  },
  {
    id: "act-odaiba",
    name: "Odaiba Seaside Park",
    category: "park",
    address: "1-4 Daiba, Minato-ku, Tokyo",
    coordinates: { lat: 35.6297, lng: 139.7746 },
    duration_minutes: 90,
    price: 0,
    currency: "USD",
    opening_hours: HOURS_ALL_DAY,
    requires_booking: false,
    indoor: false,
    description: "Waterfront park with views of Rainbow Bridge and the Statue of Liberty replica. Perfect for sunset photography with Tokyo skyline.",
    score: 0.83,
  },
  {
    id: "act-teamlab-planets",
    name: "teamLab Planets",
    category: "museum",
    address: "6-1-16 Toyosu, Koto-ku, Tokyo",
    coordinates: { lat: 35.6503, lng: 139.7899 },
    duration_minutes: 90,
    price: 32,
    currency: "USD",
    opening_hours: { monday: "09:00-22:00", tuesday: "09:00-22:00", wednesday: "09:00-22:00", thursday: "09:00-22:00", friday: "09:00-22:00", saturday: "09:00-22:00", sunday: "09:00-22:00" },
    requires_booking: true,
    indoor: true,
    description: "Walk-through immersive art where you wade through water and walk barefoot through digital landscapes. A body-immersive sensory experience.",
    score: 0.92,
  },
  // Day 5 — Shinjuku
  {
    id: "act-shinjuku-gyoen",
    name: "Shinjuku Gyoen National Garden",
    category: "park",
    address: "11 Naitomachi, Shinjuku-ku, Tokyo",
    coordinates: { lat: 35.6852, lng: 139.7100 },
    duration_minutes: 120,
    price: 5,
    currency: "USD",
    opening_hours: { monday: "Closed", tuesday: "09:00-16:00", wednesday: "09:00-16:00", thursday: "09:00-16:00", friday: "09:00-16:00", saturday: "09:00-16:00", sunday: "09:00-16:00" },
    requires_booking: false,
    indoor: false,
    description: "One of Tokyo's best cherry blossom spots with 1,000+ trees. Blends Japanese, English, and French garden styles across 144 acres.",
    score: 0.94,
  },
  {
    id: "act-golden-gai",
    name: "Golden Gai",
    category: "nightlife",
    address: "1-1 Kabukicho, Shinjuku-ku, Tokyo",
    coordinates: { lat: 35.6938, lng: 139.7040 },
    duration_minutes: 90,
    price: 25,
    currency: "USD",
    opening_hours: { monday: "19:00-01:00", tuesday: "19:00-01:00", wednesday: "19:00-01:00", thursday: "19:00-01:00", friday: "19:00-02:00", saturday: "19:00-02:00", sunday: "19:00-01:00" },
    requires_booking: false,
    indoor: true,
    description: "Labyrinth of over 200 tiny bars, each seating 5-10 people. A nostalgic post-war atmosphere with themed bars — jazz, punk, cinema, and more.",
    score: 0.89,
  },
];

// ─── Weather ──────────────────────────────────────────────────────
const FORECAST: WeatherForecast[] = [
  { date: "2026-04-01", condition: "sunny", temp_max: 19, temp_min: 11, rain_chance: 5, rain_start: null, wind_speed: 8 },
  { date: "2026-04-02", condition: "partly_cloudy", temp_max: 20, temp_min: 12, rain_chance: 15, rain_start: null, wind_speed: 10 },
  { date: "2026-04-03", condition: "sunny", temp_max: 21, temp_min: 13, rain_chance: 5, rain_start: null, wind_speed: 7 },
  { date: "2026-04-04", condition: "cloudy", temp_max: 18, temp_min: 12, rain_chance: 30, rain_start: "15:00", wind_speed: 12 },
  { date: "2026-04-05", condition: "partly_cloudy", temp_max: 20, temp_min: 11, rain_chance: 10, rain_start: null, wind_speed: 9 },
];

// ─── Destination Analysis ─────────────────────────────────────────
const DESTINATION_ANALYSIS: DestinationAnalysis = {
  forecast: FORECAST,
  alerts: [],
  weather_summary: {
    avg_temp_max: 19.6,
    avg_temp_min: 11.8,
    avg_rain_chance: 13,
    dominant_condition: "sunny",
    severe_weather_days: 0,
    packing_suggestions: [
      "Light layers for spring weather",
      "Comfortable walking shoes",
      "Compact umbrella for light rain",
      "Camera for cherry blossoms",
    ],
  },
  seasonal_events: [
    {
      name: "Cherry Blossom Festival (Hanami)",
      category: "cultural",
      description: "Peak sakura season across Tokyo's parks and gardens. Ueno Park, Shinjuku Gyoen, and Chidorigafuchi are top viewing spots.",
      month_start: 3,
      month_end: 4,
    },
    {
      name: "Golden Week Preview",
      category: "holiday",
      description: "Japan's major holiday week begins late April. Attractions may be more crowded as the holiday approaches.",
      month_start: 4,
      month_end: 5,
    },
  ],
  travel_advisories: [
    "Book cherry blossom season accommodations well in advance",
    "Carry a Suica/Pasmo IC card for seamless transit",
  ],
  analysis_timestamp: "2026-04-01T00:00:00Z",
};

// ─── Itinerary ────────────────────────────────────────────────────
const ITINERARY: OptimizedItinerary = {
  days: [
    {
      date: "2026-04-01",
      day_number: 1,
      theme: "Asakusa & Traditional Tokyo",
      weather_condition: "sunny",
      notes: "Start with Tokyo's historic heart",
      slots: [
        { activity_id: "act-sensoji", activity_name: "Senso-ji Temple", start_time: "09:00", end_time: "10:30", travel_time_from_previous_minutes: 0, notes: "Arrive early to avoid crowds" },
        { activity_id: "act-nakamise", activity_name: "Nakamise Shopping Street", start_time: "10:45", end_time: "11:45", travel_time_from_previous_minutes: 5, notes: "Try fresh melon pan and senbei" },
        { activity_id: "act-ueno-park", activity_name: "Ueno Park", start_time: "13:00", end_time: "15:00", travel_time_from_previous_minutes: 15, notes: "Cherry blossom peak — bring a picnic!" },
      ],
    },
    {
      date: "2026-04-02",
      day_number: 2,
      theme: "Shibuya, Harajuku & Digital Art",
      weather_condition: "partly_cloudy",
      notes: "Youth culture meets cutting-edge art",
      slots: [
        { activity_id: "act-meiji-shrine", activity_name: "Meiji Shrine", start_time: "09:00", end_time: "10:30", travel_time_from_previous_minutes: 0, notes: "Morning serenity in the forest" },
        { activity_id: "act-takeshita", activity_name: "Takeshita Street", start_time: "10:45", end_time: "11:45", travel_time_from_previous_minutes: 10, notes: "Kawaii culture at every corner" },
        { activity_id: "act-shibuya-crossing", activity_name: "Shibuya Crossing", start_time: "12:00", end_time: "12:30", travel_time_from_previous_minutes: 15, notes: "Watch from Shibuya Sky for best view" },
        { activity_id: "act-teamlab-borderless", activity_name: "teamLab Borderless", start_time: "14:00", end_time: "16:00", travel_time_from_previous_minutes: 20, notes: "Pre-booked tickets required" },
      ],
    },
    {
      date: "2026-04-03",
      day_number: 3,
      theme: "Imperial History & Akihabara",
      weather_condition: "sunny",
      notes: "From ancient emperors to anime culture",
      slots: [
        { activity_id: "act-imperial-palace", activity_name: "Imperial Palace East Gardens", start_time: "09:30", end_time: "11:00", travel_time_from_previous_minutes: 0, notes: "Free admission, closed Mon/Fri" },
        { activity_id: "act-akihabara", activity_name: "Akihabara Electric Town", start_time: "12:00", end_time: "14:00", travel_time_from_previous_minutes: 15, notes: "Explore multi-floor arcades and tech shops" },
        { activity_id: "act-tokyo-anime", activity_name: "Tokyo Anime Center", start_time: "14:30", end_time: "15:30", travel_time_from_previous_minutes: 5, notes: "Current exhibit: Studio Ghibli retrospective" },
      ],
    },
    {
      date: "2026-04-04",
      day_number: 4,
      theme: "Tsukiji Food & Waterfront Art",
      weather_condition: "cloudy",
      notes: "Culinary exploration and immersive art",
      slots: [
        { activity_id: "act-tsukiji", activity_name: "Tsukiji Outer Market", start_time: "08:00", end_time: "10:00", travel_time_from_previous_minutes: 0, notes: "Go early for the freshest sushi" },
        { activity_id: "act-teamlab-planets", activity_name: "teamLab Planets", start_time: "11:00", end_time: "12:30", travel_time_from_previous_minutes: 15, notes: "Wear shorts — you wade through water" },
        { activity_id: "act-odaiba", activity_name: "Odaiba Seaside Park", start_time: "14:00", end_time: "15:30", travel_time_from_previous_minutes: 20, notes: "Sunset views of Rainbow Bridge" },
      ],
    },
    {
      date: "2026-04-05",
      day_number: 5,
      theme: "Gardens & Nightlife",
      weather_condition: "partly_cloudy",
      notes: "Cherry blossoms by day, tiny bars by night",
      slots: [
        { activity_id: "act-shinjuku-gyoen", activity_name: "Shinjuku Gyoen National Garden", start_time: "09:30", end_time: "11:30", travel_time_from_previous_minutes: 0, notes: "1,000+ cherry trees in full bloom" },
        { activity_id: "act-golden-gai", activity_name: "Golden Gai", start_time: "19:00", end_time: "20:30", travel_time_from_previous_minutes: 10, notes: "200+ tiny bars — each seats ~6 people" },
      ],
    },
  ],
  unscheduled_activity_ids: [],
  optimization_method: "constraint_satisfaction + geographic_clustering",
  validation_iterations: 3,
  validation_warnings: [],
};

// ─── Full Plan ────────────────────────────────────────────────────
const DEMO_PLAN: TravelPlannerCore = {
  plan_id: "demo_tokyo_2026",
  destination: "Tokyo, Japan",
  dates: { start_date: "2026-04-01", end_date: "2026-04-06" },
  budget: { total: 5000, currency: "USD", flexibility: 0.1 },
  traveler_profile: {
    interests: ["culture", "gastronomy", "temples", "technology", "photography"],
    pace: "moderate",
    group_size: 2,
  },
  selected_flight_id: null,
  selected_hotel_id: "hotel-gracery",
  selected_activity_ids: ACTIVITIES.map((a) => a.id),
  current_cost: 3180,
  revision_count: 0,
  approval_status: "pending",
  risk_flags: [],
  alternative_plans: {},
  destination_analysis: DESTINATION_ANALYSIS,
  hotel_options: HOTELS,
  activity_options: ACTIVITIES,
  optimized_itinerary: ITINERARY,
};

export const DEMO_PLAN_RESPONSE: PlanResponse = {
  plan: DEMO_PLAN,
  map_url: "",
  pdf_url: "",
};

/** Day centroids for map fly-to (avg of activity coords per day) */
export const DAY_CENTROIDS: Record<number, { lat: number; lng: number }> = {
  1: { lat: 35.7140, lng: 139.7891 },  // Asakusa / Ueno
  2: { lat: 35.6667, lng: 139.7086 },  // Shibuya / Harajuku
  3: { lat: 35.6946, lng: 139.7657 },  // Imperial / Akihabara
  4: { lat: 35.6485, lng: 139.7784 },  // Tsukiji / Odaiba
  5: { lat: 35.6895, lng: 139.7070 },  // Shinjuku
};
